platform :ios, '7.0'
inhibit_all_warnings!
pod 'AFNetworking', '~> 2.3.1'
pod 'NSData+Base64', '~> 1.0.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'JSONKit', '~> 1.5pre'
pod 'AVOSCloud'
pod 'UMengAnalytics'
pod 'RDVTabBarController'
